default: &default
  adapter: mysql2
  pool: 20
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  host: <%= ENV['DB_HOST'] %>
  password: <%= ENV['DB_PASS'] %>

development:
  <<: *default
  database: team_dev

test:
  <<: *default
  database: test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
