default: &default
  adapter: mysql2
  pool: 20
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: dev

test:
  <<: *default
  database: test
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
